### ISSUE TITLE
Logging semantical warnings?

### ISSUE THREAD

**Issue by yorrd** [Adornis/typescript#1]
Should we even log semantical warnings? They're only summarized at the moment, not shown in detail like in the original `barbatus:typescript` package to avoid walls of warnings when compiling with symlinks to node modules. 

Will close this in a few days if there's no protest

**Comment by PopGoesTheWza** [comment]
@yorrd I have not yet tried this package. Is the issue about the typescript compiler warnings not being properly reported?

**Comment by MastroLindus** [comment]
Not really sure what fit in "semantical warnings" and what not.
However I have to say that for me it is mandatory that the compiler must output errors in the compiled files, otherwise a big advantage of using typescript instead of javascript is gone.

I am testing the latest version released on atmosphere and currently no error (syntax, wrong parameters/props/etc) is shown in the command line.
It is not possible to rely on the IDE since the IDE integration is designed to only show problems in the files opened in the editor, leaving the majoriy of unopened files unchecked.
The only way to address this in the ide is with an extra build task to run on the whole project just to detect the errors, but there's no point in having to build it again since meteor already does it once.

Also the summary of the type "X warnings in Y files" is a bit useless since you cannot really fix those warnings if you don't know which are the warnings and in which files :)

**Comment by jnoksoko** [comment]
I completely agree with @MastroLindus. There should be at least a flag to give for the compiler to print out all possible warnings and errors. This would allow developers and CI to reveal existing problems within the code base.

**Comment by yorrd** [comment]
working on a flag to show warnings... thanks for your input

**Comment by yorrd** [comment]
update is released, right now it will just log the warnings. If someone needs a flag to hide those, pull requests encouraged!
