### ISSUE TITLE
Update to Typescript 3.4

### ISSUE THREAD

**Issue by perbergland** [Adornis/typescript#10]
This new version was released on April 2 and it would be good to move to it.
I was curious as to whether that requires a new release of this package or if I can bump the typescript version used myself?

I'm mostly curious to see if the new --incremental tsc flag can speed things up

**Comment by yorrd** [comment]
the --incremental thing has already been issued in #6, let's move the discussion there :) In the coming 2-3 weeks I won't be able to look into it. If you want to take a stab, I'd welcome a pull request!

As to the issue in question here, we currently have to set the TypeScript version in our `package.js`es, not sure if it can even be done in a variable way because Meteor forces us to put a concrete version number in there. I'll update asap, thanks for the heads-up :)

**Comment by yorrd** [comment]
release x.x.9 is released with typescript 3.4.2

**Comment by perbergland** [comment]
Perfect thank you for the swift update!
I will try to carve out some time to play around with --incremental as it *should* just be a tsconfig setting.

**Comment by yorrd** [comment]
@perbergland awesome! looking forward to it
