### ISSUE TITLE
esModuleInterop doesn't seem to work.

### ISSUE THREAD

**Issue by nicu-chiciuc** [Adornis/typescript#16]
Thanks for the great package. I've been trying to add it to my current meteor project. I've managed to change multiple files but one of the biggest problems I've had was with the imports from ts->js or js->ts. 
In .jsx react files I had to transform:
```
import React, { Component } from 'react';
```
to
```
import * as React from 'react';
import { Component } from 'react';
```

I've tried setting 'allowSyntheticDefaultImports' and/or 'esModuleInterop' to true but nothing seems to work as expected.
Do you know if it's even possible to maintain the old type of imports (`import React from 'react';`) while using this package (implying that the project will contain both .js and .ts files).

**Comment by yorrd** [comment]
uhhh I have no clue about react. 

In our projects, we are using default imports like `import default from 'package';` quite frequently. To be honest, I don't even know if the package supports react at the moment because I've never tried `.jsx` compilation with it. Just a sanity check: there is an old unmaintained(!) version of this at `barbatus:typescript`. Could you try switching this package with that one and see if it compiles? Maybe I broke `jsx`-support in the process of modernizing the package.

**Comment by nicu-chiciuc** [comment]
The problem wasn't just with React. Basically everything worked fine when `esModuleInterop` was turned off (by default), but a lot of imports (specifically from other js files) had to be transformed into the star notation imports. That shouldn't be necessary, so I tried to find a solution for it. Using the `esModuleInterop` seemed to solve this problem but caused other imports to fail.
I will have to dig into the Meteor build systems more to figure out how everything works together.

Do you use both js and ts in your project?

Also, this issue can be closed since I will need to get more info until opening a new one.

**Comment by yorrd** [comment]
Alright, thanks for investigating this. We don't use any JavaScript in our projects. Curious to see how you get this fixed.

**Comment by smeijer** [comment]
@nicu-chiciuc, I'm having the same problem, which makes gradually migrating to typescript difficult. It would require to export the components differently than our current convention. (`export { Button }` instead of `export default Button`)

And besides the "differently", I'm not a big fan of the `import { Button } from 'lib/Button'` syntax either.

Did you find a solution?

**Comment by nicu-chiciuc** [comment]
Unfortunately I did not. It is possible to have both JS and TS using the `default` syntax (e. g. create-react-app with typescript). So I guess it has something to do with the Meteor build system. I've tried to look inside but I don't have the expertise nor the time to figure any good solution. 
For the time being we've returned to using `@ts-check` and type the project incrementally using comments.

**Comment by smeijer** [comment]
Yes, I've been reading into this. And it seems that it has to do with a babel transformer. Guess there is a difference in plugins there between CRA and meteor.

There was an active discussion going in the typescript repo, and it seems that they won't fix/change anything anytime soon.

**Comment by smeijer** [comment]
This post summed it up quite nice for me:

https://github.com/Microsoft/TypeScript/issues/5565#issuecomment-155171298
