### ISSUE TITLE
comparison with official 'typescript' package.

### ISSUE THREAD

**Issue by trusktr** [Adornis/typescript#25]
Hello! 

Would you mind detailing what the difference with this package and the official `typescript` package are?

**Comment by CarlQLange** [comment]
I think that this module has support for `tsconfig.json` where the official `typescript` package doesn't. I'm sure there are other differences though, I don't know anything really :) I'd be interested in hearing from the author as well.

**Comment by CarlQLange** [comment]
This package also doesn't seem to support dynamic imports in the same way as the main package does, although that might just be my configuration.

**Comment by yorrd** [comment]
@trusktr this package was made quite some time ago, because the old `barbatus:typescript` was having some performance issues for us and didn't get updated to the newer versions. We hard-forked it and stripped it down in some places just to get a solution running for our team. Benjamn always said there was going to be an official one, so we switched to the official one now. 

The reason I didn't shut this off yet is (as detailed in bejamns post on the meteor PR and as mentioned by @CarlQLange ) that the official solution still doesn't use the `tsconfig.json`, which this package does. Some people asked me to keep this package running until that's resolved so we did. Honestly, I'd much rather use the official one, if only there was some movement there to support typescript fully :thinking: 

I do see you every now and then on the forums and the issue tracker, any opinion on this is much appreciated.
